import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-4 p-4 border-b border-gray-200">
          <a href="/" className="font-semibold">Home</a>
          <a href="/chat">Chat</a>
          <a href="/inbox">Inbox</a>
          <a href="/calendar">Calendar</a>
          <a href="/admin/marketplace">Marketplace</a>
        </nav>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
